name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: 1lch2/Frontend_Notes
        TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && cd -
        BUILD_DIR: docs/.vuepress/dist